### ISSUE TITLE
"generateRickroll is not defined"

### ISSUE THREAD

**Issue by Matto58** [NihalNavath/Rickroll-Generator#3]
Hello! I was trying to rickroll my friends, but every time I try to, it shows this error message in the console.
_(PS: I'm using Edge 93.0.961.47 on Windows 10 x64 build 19042.1237 if that helps)_
![console](https://user-images.githubusercontent.com/60749494/133815420-50a85611-6010-457f-bd24-9190d5bade7f.jpg)

**Comment by NihalNavath** [comment]
Oh, my bad had commented out the script that handles creating rr links, and had pushed to production server.

Thanks for reporting, it has been fixed.
